<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
</head>
<body>
<form method="post" action="/signUp">
    <input name="firstName" placeholder="First Name">
    <input name="lastName" placeholder="Last Name">
    <input name="email" placeholder="Email">
    <input name="password" placeholder="Password">
    <input type="submit" value="Sign Up">
</form>
</body>
</html>