<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/products/update" method="post">
    <label>
        <input placeholder="Id" name="id" type="number">
    </label>

    <label>
        <input placeholder="name" name="name" type="text">
    </label>

    <label>
        <input placeholder="weight" name="weight" type="number">
    </label>
    <br>
    <input type="submit" placeholder="submit">
</form>
</body>
</html>